ALTER TABLE Sales 
    DROP FOREIGN KEY sales_ibfk_1;

ALTER TABLE Sales
    MODIFY COLUMN SaleDate DATE NOT NULL DEFAULT (CURRENT_DATE),
    MODIFY COLUMN ProductID INT NOT NULL;

ALTER TABLE Sales
    ADD CONSTRAINT fk_sales_product FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON DELETE RESTRICT;